### ISSUE TITLE
Automate review of simulator contributions

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#1326]
Some options for accepting contributions from collaborators so they can maintain their simulation tools
- Grant access to the API
- Ask collaborators to either post an issue to the Git repo 
  - Ask for a link to the properties file
  - An action could be setup to review the contribution
    - Validate the properties
    - Use the test suite to validate the image
    - If the tests succeed, report success
    - If the tests fail, report errors
  - A second action could be setup on closing the issues
   - Use the simulators API to commit the new metadata to the database 
  - Potentially, the BioSimulators team could have the opportunity to review the contribution or issues could be closed automatically if the tests are successful
- Something similar could be setup with pull requests, but pull requests are more cumbersome for contributors
  - This could be used to require developers to contribute their Dockerfile and properties.json file
  - This has some advantages for provenance and revisioning, but its more cumbersome for contributors. 
  - If we wanted to go this route, we should use a separate repo because the Biosimulations repo is quite large
  - For these reasons, I think issues are a better choice

**Comment by bilalshaikh42** [comment]
The action would be on the Biosimulators organization, correct? I am unsure what you mean regarding  the seperate repo. Each simulator would have the action to post to the API.  Maintainers would file a pull request to make changes. The pull request would run tests against the schema. I was already planning to sync the database entries with the properties.json file for each repo in the Biosimulators organization

**Comment by jonrkarr** [comment]
I'm marking this as something to do in the future. At least at the beginning, we need manually review contributions. I think this would take a day or couple days to set this up well.

**Comment by jonrkarr** [comment]
I think a good path might be for developers to submit simulators (or new versions, or revisions to versions) as issues to the BioSimulations repo. 

(Better yet, maybe we should create a BioSimulators repo and have issues posted there. This would avoid the current confusion caused by asking people to submit issues related to BioSimulators to the BioSimulations repo. At least for now, this repo could just be a place to collect issues related to BioSimulators. The repo could be empty except for a README file.)

I see a few advantages of using GitHub issues over a webform or direct contribution to the API
- It creates opportunity for us to manually review contributions
- It creates a place for conversation about issues about submissions between us and the contributor
- It leverages GitHub accounts to keep track of who contributed simulators
- We can use GitHub actions to check the contributed container and its properties -- I think this would be easier than trying to setup similar checking that runs on the BioSimulations server upon POST requests

**Comment by jonrkarr** [comment]
The Journal of Open Source Software (JOSS) and BioContainers are both using GitHub actions for workflows along these lines. JOSS uses a webform that generates GitHub issues. BioContainers uses pull requests. Both have setup automated actions to review contributions upon the creation of issues or pull requests.

**Comment by jonrkarr** [comment]
Sketching out workflows

```
name: Validate simulator

on:
  issues:
    types: [opened]
	
jobs:
  validate:
	name: Validate simulator
	runs-on: ubuntu-latest
	if: ${{ contains(github.event.issues.labels.*.name, 'Submit simulator' }}
	steps:
	- name: Parse URL for specifications from issue
	  run: |
		adf
		
	- name: Validate specifications
	- name: Post comment about success/error to issue
	
	- name: Validate simulator
	- name: Post comment about success/error to issue
	  run: |
		curl -u biosimulators-daemon:${GH_ISSUES_ACCESS_TOKEN} https://api.github.com/repos/biosimulators/Biosimulators/issues/${ISSUE_NUMBER} \
		  --request PATCH \
		  --header "Content-Type: application/json"
		  --data '{"body": ""}	
```
	
```
name: Integrate simulator

on:
  issues:
    types: [closed]
	
jobs:
  integrate:
	name: Integrate simulator
	runs-on: ubuntu-latest
	if: ${{ contains(github.event.issues.labels.*.name, 'Submit simulator' }}
	steps:
	- name: Parse URL for specifications from issue
	
	- name: Post simulator to database
	
	- name: Post comment about success/failure to issue
		
	
```
