### ISSUE TITLE
Example vcell runs failing

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2633]
https://run.biosimulations.dev/simulations/60ca36d3ec4fbea4a994933d#tab=log

VCell seems to have a problem with the way the sedml set up. The error is below 
```
17:37:35 [main] ERROR cbit.vcell.solvers.AbstractSolver - simulation failed at time=1.3: consider using smaller default or max time step.
values are:
A = NaN
C = Infinity
PrmA = Infinity
PrmA_bound = -Infinity
PrmR = Infinity
PrmR_bound = -Infinity
R = -Infinity

cbit.vcell.solver.SolverException: simulation failed at time=1.3: consider using smaller default or max time step.
values are:
A = NaN
C = Infinity
PrmA = Infinity
PrmA_bound = -Infinity
PrmR = Infinity
PrmR_bound = -Infinity
R = -Infinity

	at cbit.vcell.solver.ode.DefaultODESolver.check(DefaultODESolver.java:102) ~[vcell-core-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at cbit.vcell.solver.ode.DefaultODESolver.integrate(DefaultODESolver.java:560) ~[vcell-core-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at cbit.vcell.solver.ode.AbstractJavaSolver.runSolver(AbstractJavaSolver.java:166) [vcell-core-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.vcell.cli.SolverHandler.simulateAllTasks(SolverHandler.java:106) [vcell-cli-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.vcell.cli.CLIStandalone.singleExecOmex(CLIStandalone.java:188) [vcell-cli-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at org.vcell.cli.CLIStandalone.main(CLIStandalone.java:65) [vcell-cli-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
Solver status: 3
Solver message: simulation failed at time=1.3: consider using smaller default or max time step.
values are:
A = NaN
C = Infinity
PrmA = Infinity
PrmA_bound = -Infinity
PrmR = Infinity
PrmR_bound = -Infinity
R = -Infinity

Failed execution: Model 'Vilar-PNAS-2002-minimal-circardian-clock__ODE_deterministic' Task 'tsk_0_2'.

```

**Comment by jonrkarr** [comment]
This looks like a new VCell issue. The SED-ML hasn't changed recently.

**Comment by moraru** [comment]
This is not a bug, it is a feature :)  The failure is by design.  The SED-ML exercised algorithm parameters and error messages.  Task 2 simulation calls for a fixed time-step solver (Forward Euler) with no parameters and the model us too stiff for the default timestep and the solver no longer converges and crashes after simulating a little more than 1 second.  The error message  correctly suggests using a smaller timestep.  Another task in the same  SED-ML does exactly that, by specifying smaller timestep using custom algorithm parameter, and that task succeeds.

**Comment by moraru** [comment]
@jonrkarr shall we close this?

**Comment by moraru** [comment]
@bilalshaikh42 Does the UI pass along the beginning of the message to the user or does the user need to look at the log? The first line of the message gives the most important info: "17:37:35 [main] ERROR cbit.vcell.solvers.AbstractSolver - simulation failed at time=1.3: consider using smaller default or max time step."

**Comment by bilalshaikh42** [comment]
The UI is not able to display the errors since there is no "log.yml" output. I do see a "status.yml" output, but that file shows that everything has succeeded

**Comment by bilalshaikh42** [comment]
```
sedDocuments:
  simulation.sedml:
    outputs:
      plot2d_Euler_default:
        curves:
          plot2d_Euler_default_curve_0: SUCCEEDED
          plot2d_Euler_default_curve_1: SUCCEEDED
          plot2d_Euler_default_curve_2: SUCCEEDED
          plot2d_Euler_default_curve_3: SUCCEEDED
          plot2d_Euler_default_curve_4: SUCCEEDED
          plot2d_Euler_default_curve_5: SUCCEEDED
          plot2d_Euler_default_curve_6: SUCCEEDED
          plot2d_Euler_default_curve_7: SUCCEEDED
          plot2d_Euler_default_curve_8: SUCCEEDED
        status: SUCCEEDED
      plot2d_Euler_small_step_size:
        curves:
          plot2d_Euler_small_step_size_curve_0: SUCCEEDED
          plot2d_Euler_small_step_size_curve_1: SUCCEEDED
          plot2d_Euler_small_step_size_curve_2: SUCCEEDED
          plot2d_Euler_small_step_size_curve_3: SUCCEEDED
          plot2d_Euler_small_step_size_curve_4: SUCCEEDED
          plot2d_Euler_small_step_size_curve_5: SUCCEEDED
          plot2d_Euler_small_step_size_curve_6: SUCCEEDED
          plot2d_Euler_small_step_size_curve_7: SUCCEEDED
          plot2d_Euler_small_step_size_curve_8: SUCCEEDED
        status: SUCCEEDED
      plot2d_Fig_1_c:
        curves:
          plot2d_Fig_1_ccurve_0: SUCCEEDED
          plot2d_Fig_1_ccurve_1: SUCCEEDED
          plot2d_Fig_1_ccurve_2: SUCCEEDED
          plot2d_Fig_1_ccurve_3: SUCCEEDED
          plot2d_Fig_1_ccurve_4: SUCCEEDED
          plot2d_Fig_1_ccurve_5: SUCCEEDED
          plot2d_Fig_1_ccurve_6: SUCCEEDED
          plot2d_Fig_1_ccurve_7: SUCCEEDED
          plot2d_Fig_1_ccurve_8: SUCCEEDED
        status: SUCCEEDED
      plot2d_Fig_1a:
        curves:
          plot2d_Fig_1a_curve_0: SUCCEEDED
          plot2d_Fig_1a_curve_1: SUCCEEDED
          plot2d_Fig_1a_curve_2: SUCCEEDED
          plot2d_Fig_1a_curve_3: SUCCEEDED
          plot2d_Fig_1a_curve_4: SUCCEEDED
          plot2d_Fig_1a_curve_5: SUCCEEDED
          plot2d_Fig_1a_curve_6: SUCCEEDED
          plot2d_Fig_1a_curve_7: SUCCEEDED
          plot2d_Fig_1a_curve_8: SUCCEEDED
        status: SUCCEEDED
      plot2d_low_delta_R_det:
        curves:
          plot2d_low_delta_R_detcurve_0: SUCCEEDED
          plot2d_low_delta_R_detcurve_1: SUCCEEDED
          plot2d_low_delta_R_detcurve_2: SUCCEEDED
          plot2d_low_delta_R_detcurve_3: SUCCEEDED
          plot2d_low_delta_R_detcurve_4: SUCCEEDED
          plot2d_low_delta_R_detcurve_5: SUCCEEDED
          plot2d_low_delta_R_detcurve_6: SUCCEEDED
          plot2d_low_delta_R_detcurve_7: SUCCEEDED
          plot2d_low_delta_R_detcurve_8: SUCCEEDED
        status: SUCCEEDED
      plot2d_low_delta_R_stoch:
        curves:
          plot2d_low_delta_R_stochcurve_0: SUCCEEDED
          plot2d_low_delta_R_stochcurve_1: SUCCEEDED
          plot2d_low_delta_R_stochcurve_2: SUCCEEDED
          plot2d_low_delta_R_stochcurve_3: SUCCEEDED
          plot2d_low_delta_R_stochcurve_4: SUCCEEDED
          plot2d_low_delta_R_stochcurve_5: SUCCEEDED
          plot2d_low_delta_R_stochcurve_6: SUCCEEDED
          plot2d_low_delta_R_stochcurve_7: SUCCEEDED
          plot2d_low_delta_R_stochcurve_8: SUCCEEDED
        status: SUCCEEDED
      report_Euler_default:
        dataSets:
          dataSet_2_0: SUCCEEDED
          dataSet_2_1: SUCCEEDED
          dataSet_2_2: SUCCEEDED
          dataSet_2_3: SUCCEEDED
          dataSet_2_4: SUCCEEDED
          dataSet_2_5: SUCCEEDED
          dataSet_2_6: SUCCEEDED
          dataSet_2_7: SUCCEEDED
          dataSet_2_8: SUCCEEDED
          dataSet_2_time: SUCCEEDED
        status: SUCCEEDED
      report_Euler_small_step_size:
        dataSets:
          dataSet_3_0: SUCCEEDED
          dataSet_3_1: SUCCEEDED
          dataSet_3_2: SUCCEEDED
          dataSet_3_3: SUCCEEDED
          dataSet_3_4: SUCCEEDED
          dataSet_3_5: SUCCEEDED
          dataSet_3_6: SUCCEEDED
          dataSet_3_7: SUCCEEDED
          dataSet_3_8: SUCCEEDED
          dataSet_3_time: SUCCEEDED
        status: SUCCEEDED
      report_Fig_1_c:
        dataSets:
          dataSet_4_0: SUCCEEDED
          dataSet_4_1: SUCCEEDED
          dataSet_4_2: SUCCEEDED
          dataSet_4_3: SUCCEEDED
          dataSet_4_4: SUCCEEDED
          dataSet_4_5: SUCCEEDED
          dataSet_4_6: SUCCEEDED
          dataSet_4_7: SUCCEEDED
          dataSet_4_8: SUCCEEDED
          dataSet_4_time: SUCCEEDED
        status: SUCCEEDED
      report_Fig_1a:
        dataSets:
          dataSet_0_0: SUCCEEDED
          dataSet_0_1: SUCCEEDED
          dataSet_0_2: SUCCEEDED
          dataSet_0_3: SUCCEEDED
          dataSet_0_4: SUCCEEDED
          dataSet_0_5: SUCCEEDED
          dataSet_0_6: SUCCEEDED
          dataSet_0_7: SUCCEEDED
          dataSet_0_8: SUCCEEDED
          dataSet_0_time: SUCCEEDED
        status: SUCCEEDED
      report_low_delta_R_det:
        dataSets:
          dataSet_1_0: SUCCEEDED
          dataSet_1_1: SUCCEEDED
          dataSet_1_2: SUCCEEDED
          dataSet_1_3: SUCCEEDED
          dataSet_1_4: SUCCEEDED
          dataSet_1_5: SUCCEEDED
          dataSet_1_6: SUCCEEDED
          dataSet_1_7: SUCCEEDED
          dataSet_1_8: SUCCEEDED
          dataSet_1_time: SUCCEEDED
        status: SUCCEEDED
      report_low_delta_R_stoch:
        dataSets:
          dataSet_5_0: SUCCEEDED
          dataSet_5_1: SUCCEEDED
          dataSet_5_2: SUCCEEDED
          dataSet_5_3: SUCCEEDED
          dataSet_5_4: SUCCEEDED
          dataSet_5_5: SUCCEEDED
          dataSet_5_6: SUCCEEDED
          dataSet_5_7: SUCCEEDED
          dataSet_5_8: SUCCEEDED
          dataSet_5_time: SUCCEEDED
        status: SUCCEEDED
    status: SUCCEEDED
    tasks:
      tsk_0_0:
        status: SUCCEEDED
      tsk_0_1:
        status: SUCCEEDED
      tsk_0_2:
        status: SUCCEEDED
      tsk_0_3:
        status: SUCCEEDED
      tsk_1_0:
        status: SUCCEEDED
      tsk_1_1:
        status: SUCCEEDED
status: SUCCEEDED
```
