### ISSUE TITLE
Fix Nx Cloud Report warnings (We didn't find any information for the current pull request ...)

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/CRBM-Viz#2733]
I think this can be fixed by replacing the `NX_BRANCH` environment variable for each job 
```yaml
...
jobs:
  getAffectedLibrariesApps:
    env:
        NX_BRANCH: ${{ github.event.pull_request.head.ref }}  
...
```

with a global variable
```yaml
env:
  NX_BRANCH: ${{ github.event.pull_request.head.ref }}  
```

I wasn't sure if @bilalshaikh42 intentionally set up this environmental variable this way.
