### ISSUE TITLE
Mapping of metadata fields to predicates/identifiers

### ISSUE THREAD

**Issue by bilalshaikh42** [reproducible-biomedical-modeling/CRBM-Viz#2752]
```yaml
title: "https://dublincore.org/specifications/dublin-core/dcmi-terms/title"
abstract: "https://dublincore.org/specifications/dublin-core/dcmi-terms/abstract"
keyword: "http://prismstandard.org/namespaces/basic/2.0/keyword"
thumbnail: "http://www.collex.org/schema#thumbnail"
description: "https://dublincore.org/specifications/dublin-core/dcmi-terms/description"
taxa: "http://biomodels.net/biology-qualifiers/hasTaxon"
encodes: "http://biomodels.net/biology-qualifiers/encodes"
source: "http://dublincore.org/specifications/dublin-core/dcmi-terms/source"
predecessor: "http://biomodels.net/model-qualifiers/isDerivedFrom"
successor: "http://purl.org/spar/scoro/successor"
seeAlso: "http://www.w3.org/2000/01/rdf-schema#seeAlso"
identifier: "http://biomodels.net/model-qualifiers/is"
citation: "http://biomodels.net/model-qualifiers/isDescribedBy"
license: "https://dublincore.org/specifications/dublin-core/dcmi-terms/licence"
creator: "https://dublincore.org/specifications/dublin-core/dcmi-terms/creator"
contributor: "https://dublincore.org/specifications/dublin-core/dcmi-terms/contributor"
funder: "http://purl.org/spar/scoro/funder"
created: "https://dublincore.org/specifications/dublin-core/dcmi-terms/created"
modified: "https://dublincore.org/specifications/dublin-core/dcmi-terms/modified"
```
